theme: jekyll-theme-minimal
google-site-verification: google9fad11adbc3c3deb.html
logo: "https://avatars.githubusercontent.com/u/64524975?v=4"
show_downloads: false
title: [Cristina Garcia Holgado]
description: []
